/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_spookybox_freenect_DepthStreamCallback */

#ifndef _Included_com_spookybox_freenect_DepthStreamCallback
#define _Included_com_spookybox_freenect_DepthStreamCallback
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_spookybox_freenect_DepthStreamCallback
 * Method:    depthCallback
 * Signature: (Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_com_spookybox_freenect_DepthStreamCallback_depthCallback
  (JNIEnv *, jclass, jobject, jobject, jobject);

/*
 * Class:     com_spookybox_freenect_DepthStreamCallback
 * Method:    initGammaArray
 * Signature: (Ljava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_com_spookybox_freenect_DepthStreamCallback_initGammaArray
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
